-- INIT database
CREATE TABLE CCUSTO (
  CCusto VARCHAR(3) NOT NULL,
  NomeCC VARCHAR(10) NOT NULL,
  
  CONSTRAINT PK_CCUSTO PRIMARY KEY(CCusto)
);

CREATE TABLE SECAO (
  Secao NUMERIC(3) NOT NULL,
  NomeSec VARCHAR(20) NOT NULL,
  CCusto VARCHAR(3) NOT NULL,
  
  CONSTRAINT PK_SECAO PRIMARY KEY(Secao),
  CONSTRAINT FK_SECAO_CCUSTO FOREIGN KEY(CCusto) REFERENCES CCUSTO(CCusto)
);

CREATE TABLE ALMOXARIFE (
  NAlmox NUMERIC(4) NOT NULL,
  Almoxarife VARCHAR(30) NOT NULL,
  
  CONSTRAINT PK_ALMOXARIFE PRIMARY KEY(NAlmox)
);

CREATE TABLE REQUISICAO (
  NumReq NUMERIC(7) NOT NULL,
  DtReq DATETIME(10) NOT NULL,
  Secao NUMERIC(3) NOT NULL,
  NAlmox NUMERIC(4) NOT NULL,
  
  CONSTRAINT PK_REQUISICAO PRIMARY KEY(NumReq),
  CONSTRAINT FK_REQUISCAO_SECAO FOREIGN KEY(Secao) REFERENCES SECAO(Secao),
  CONSTRAINT FK_REQUISICAO_ALMOXARIFE FOREIGN KEY(NAlmox) REFERENCES ALMOXARIFE(NAlmox)
);

CREATE TABLE MATERIAL (
  CdMat NUMERIC(4) NOT NULL,
  DescrMatPrima VARCHAR(15) NOT NULL,
  
  CONSTRAINT PK_MATERIAL PRIMARY KEY(CdMat)
);

CREATE TABLE REQ_MAT (
  NumReq NUMERIC(7) NOT NULL,
  CdMat NUMERIC(4) NOT NULL,
  QtdReq NUMERIC(7) NOT NULL,
  VlrUnit DECIMAL(10,2) NOT NULL,
  
  CONSTRAINT PK_REQ_MAT PRIMARY KEY(NumReq),
  CONSTRAINT FK_REQ_MAT_REQUISICAO FOREIGN KEY(NumReq) REFERENCES REQUISICAO(NumReq),
  CONSTRAINT FK_REQ_MAT_MATERIAL FOREIGN KEY(CdMat) REFERENCES MATERIAL(CdMat)
);
